gem 'json'
gem 'mechanize'
gem 'nokogiri'
gem 'awesome_print'
gem 'pry'
gem 'hashie'
gem 'rspec', '<3.0 '
gem 'net-ssh'
gem 'page-object'
gem 'selenium-webdriver'
gem 'headless'
gem 'timeout'
gem 'onapp_market', '1.8.0', git: 'git@bitbucket.org:onappcore/marketapi.git', branch: 'master'
gem 'fog-onapp', '1.9.0', path: '/home/roman/fog-onapp'
gem 'fog-json'
gem 'rspec_junit_formatter'
gem 'activesupport'