gem 'json'
gem 'mechanize', '2.7.5'
gem 'nokogiri'
gem 'ipaddress'
gem 'awesome_print'
gem 'pry'
gem 'hashie'
gem 'rspec', '<3.0 '
gem 'net-ssh'
gem 'page-object'
gem 'selenium-webdriver'
gem 'headless'
gem 'timeout'
gem 'onapp_market', '1.18.0', git: 'git@bitbucket.org:onappcore/marketapi.git', branch: 'master'
# gem 'fog-onapp', '1.18.0', git: 'git@bitbucket.org:onappcore/fog-onapp.git', branch: 'master'
# gem 'fog-json'
gem 'rspec_junit_formatter'
gem 'activesupport'
gem 'faker'
gem 'rest-client', '1.6.9'
